export interface ICliente {
    id: number,
    nome: string,
    cpf: number,
    cor: string,
    estadoCivil: string,
    sexo: string,
    pai: string,
    mae: string,
    dataNascimento: string,
    profissao: string,
    indicacao: string,
    endereco: string,
    numero: number,
    complemento: string,
    bairro: string,
    municipio: string,
    uf: string,
    cep: string,
    telefoneResidencial: string,
    telefoneComercial: string,
    telefoneCelular: string,
    email: string
}